"""Reference-value tests for the Brant proportional-odds diagnostic.

The reference values are produced by R ``brant::brant(MASS::polr(...))`` on the
shared fixture ``sim/fixtures/brant_po_holds.csv`` (generated by
``sim/oracles/make_brant_fixture.py``, consumed by ``sim/oracles/brant_reference.R``).
The python test and the R oracle read the same CSV rows, so the R output is the
exact reference for this fixture. Reference wins over any literal (SPEC R19);
tolerances are never loosened to pass.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from metajudge.dif import _brant_test  # type: ignore[reportPrivateUsage]

_FIXTURES = Path(__file__).resolve().parents[1] / "sim" / "fixtures"
_HOLDS = _FIXTURES / "brant_po_holds.csv"
_VIOLATED = _FIXTURES / "brant_po_violated.csv"

# Pinned from: Rscript sim/oracles/brant_reference.R  (PO holds by construction).
R_OMNIBUS_CHI2 = 1.5026440
R_OMNIBUS_DF = 4
R_OMNIBUS_P = 0.8261730
R_X1_CHI2 = 0.4740277
R_X2_CHI2 = 1.1893670

# Pinned from the same oracle on the PO-violated fixture (x1 slope drifts across
# cutpoints; x2 stays proportional). This locks the cross-cutpoint covariance under
# violation, the regime where it does its load-bearing work (SPEC R19).
RV_OMNIBUS_CHI2 = 136.536997
RV_X1_CHI2 = 133.624796
RV_X2_CHI2 = 2.430403


def _load(path: Path) -> tuple[np.ndarray, np.ndarray]:
    frame = pd.read_csv(path)
    endog = frame["y"].to_numpy(dtype=np.int_)
    exog = frame[["x1", "x2"]].to_numpy(dtype=np.float64)
    return endog, exog


def test_brant_omnibus_matches_r_reference() -> None:
    endog, exog = _load(_HOLDS)
    res = _brant_test(endog, exog, names=["x1", "x2"])
    assert res.converged
    assert res.omnibus_df == R_OMNIBUS_DF
    # The engine and R brant read the same rows, so the only gap is the covariance-of-slopes
    # estimator; measured agreement is ~7e-4 (omnibus) and ~5e-5 (per-predictor). Tolerances
    # are pinned an order of magnitude tighter than that gap so a real discrepancy in the
    # cross-cutpoint covariance -- the quantity Brant validates -- cannot hide (was rel=0.02,
    # ~27x too loose to catch it).
    assert res.omnibus_chi2 == pytest.approx(R_OMNIBUS_CHI2, rel=2e-3)
    assert res.omnibus_p == pytest.approx(R_OMNIBUS_P, abs=1e-3)


def test_brant_per_predictor_matches_r_reference() -> None:
    endog, exog = _load(_HOLDS)
    res = _brant_test(endog, exog, names=["x1", "x2"])
    c1, df1, _ = res.per_predictor["x1"]
    c2, df2, _ = res.per_predictor["x2"]
    assert df1 == 2
    assert df2 == 2
    assert c1 == pytest.approx(R_X1_CHI2, rel=1e-3)
    assert c2 == pytest.approx(R_X2_CHI2, rel=1e-3)


def test_brant_magnitude_matches_r_reference_under_violation() -> None:
    # The load-bearing case: the cross-cutpoint covariance is what makes the statistic
    # correct, and it only bites when PO is violated. Pin the omnibus and per-predictor
    # magnitudes against R brant, and confirm the violation localizes to x1 (x2 stays
    # proportional and is NOT flagged).
    endog, exog = _load(_VIOLATED)
    res = _brant_test(endog, exog, names=["x1", "x2"])
    assert res.converged
    assert res.omnibus_chi2 == pytest.approx(RV_OMNIBUS_CHI2, rel=2e-3)
    c1, _, p1 = res.per_predictor["x1"]
    c2, _, p2 = res.per_predictor["x2"]
    assert c1 == pytest.approx(RV_X1_CHI2, rel=1e-3)
    assert c2 == pytest.approx(RV_X2_CHI2, rel=1e-3)
    assert p1 < 1e-3  # x1 non-proportional -> flagged
    assert p2 > 0.05  # x2 proportional -> not flagged


def test_brant_flags_nonproportional_slopes() -> None:
    # PO violation by construction: the slope of x1 grows across cutpoints, so the
    # parallel-lines assumption is false. Brant should reject for x1 and overall.
    rng = np.random.default_rng(7)
    n = 1500
    x1 = rng.standard_normal(n)
    p_lo = 1.0 / (1.0 + np.exp(-(1.4 - 0.2 * x1)))
    p_mid = 1.0 / (1.0 + np.exp(-(0.2 - 1.3 * x1)))
    p_hi = 1.0 / (1.0 + np.exp(-(-1.0 - 2.2 * x1)))
    u = rng.random(n)
    y = (u > p_lo).astype(int) + (u > p_mid).astype(int) + (u > p_hi).astype(int)
    res = _brant_test(y.astype(np.int_), x1[:, None], names=["x1"])
    assert res.converged
    assert res.per_predictor["x1"][2] < 1e-3  # PO violated -> small p
    assert res.omnibus_p < 1e-3
