# Pinned reference values for the Brant proportional-odds test.
# Reads the shared fixtures sim/fixtures/brant_po_{holds,violated}.csv (generated by
# sim/oracles/make_brant_fixture.py) so the python test and this oracle see the same
# rows. Run:
#   Rscript sim/oracles/brant_reference.R
# Pin the printed Omnibus and per-predictor X2/df/probability into
# tests/test_diagnostics.py with this script path as provenance.
suppressMessages({ library(MASS); library(brant) })

args <- commandArgs(trailingOnly = FALSE)
script_path <- sub("^--file=", "", args[grep("^--file=", args)])
root <- normalizePath(file.path(dirname(script_path), "..", ".."))

run_one <- function(name) {
  csv <- file.path(root, "sim", "fixtures", name)
  d <- read.csv(csv)
  d$y <- factor(d$y, ordered = TRUE)
  m <- polr(y ~ x1 + x2, data = d, Hess = TRUE)
  cat("\n=== brant() on", name, "===\n")
  print(brant(m))
}

run_one("brant_po_holds.csv")
run_one("brant_po_violated.csv")
