"""Worked example: audit three SummEval dimensions for extractive/abstractive DIF.

Runnable end to end on a fresh clone, no data setup:

    uv run python examples/audit_summeval_consistency.py

What this audits: the same SummEval (Fabbri et al. 2020) EXPERT panel as
examples/audit_summeval.py -- 3 human expert raters scoring 1600 summaries (100
articles x 16 systems), stratified extractive vs abstractive -- but on the
CONSISTENCY, FLUENCY, and RELEVANCE annotation dimensions instead of coherence.

Design, pre-registered before this script was ever run against the data (full
record in docs/decisions/2026-07-04-e07-summeval-consistency-dif.md):

- Dimensions and their pre-registered rank: consistency (PRIMARY -- extractive
  summaries lift sentences verbatim, so factual consistency with the source is
  near-guaranteed, while abstractive generation can hallucinate; this makes
  consistency the dimension most exposed to an extractive/abstractive quality
  gap), fluency (SECONDARY), relevance (EXPLORATORY -- included for completeness,
  no strong a-priori direction). All three were named and ranked before any of
  them was run, so this is one pre-registered family, not a post-hoc sweep.
- focal = abstractive, reference = extractive (the same pair as audit_summeval.py).
- Conditioner: external, leave-one-dimension-out (LODO). For the dimension under
  audit, the per-item mean over raters of the OTHER three annotation dimensions.
  This is independent of the studied dimension's own score, the property an
  external conditioner needs
  (docs/decisions/2026-06-22-e07-dif-ordinal-logistic-regression.md).
- Holm-corrected across the three dimensions.

Headline result (full record in the findings doc): the PRIMARY analysis
(consistency) finds a decisive nonuniform DIF (chi2=56.23, p<1e-11, Holm-adjusted
p<1e-11) -- the abstractive/extractive difference lives in the INTERACTION with
quality, not a flat offset -- yet the effect-size magnitude is Jodoin-Gierl class
A (Nagelkerke R2 delta 0.0146), well inside the negligible band, and the
cluster-robust CI does not clear it either ([0.0063, 0.0295], 400 resamples).
Statistically decisive, practically negligible: the report card's own
significance-vs-magnitude framing
(docs/decisions/2026-07-02-e07-overlap-threshold-calibration.md), sharper here
than the shipped coherence demo (this Holm-adjusted p is many orders past the
coherence demo's p=0.0005, but the R2 delta is smaller).

Data: examples/data/summeval_dims.csv, generated by
`scripts/prep_demo.py --jsonl <path> --multi-dim` from the SummEval JSONL
(MIT-licensed; not vendored here -- see src/metajudge/data/SOURCE.md). One row per
(item, rater): item, rater, stratum, and all four annotation dimensions
(coherence, consistency, fluency, relevance) as columns, so the LODO conditioner
above is reproducible from the committed CSV alone.

Expected output is committed alongside this script as
`examples/sample_output_summeval_consistency.txt`.
"""

from __future__ import annotations

from collections.abc import Hashable
from pathlib import Path

import pandas as pd

from metajudge import ReportCard, audit
from metajudge.data import Ratings
from metajudge.dif import holm_adjust

HERE = Path(__file__).parent
DATA_PATH = HERE / "data" / "summeval_dims.csv"

ALL_DIMS = ["coherence", "consistency", "fluency", "relevance"]
AUDITED_DIMS = ["consistency", "fluency", "relevance"]  # pre-registered order
ROLE = {"consistency": "PRIMARY", "fluency": "SECONDARY", "relevance": "EXPLORATORY"}

FOCAL = "abstractive"
REFERENCE = "extractive"
N_BOOT = 400
SEED = 7


def load_data(path: Path = DATA_PATH) -> pd.DataFrame:
    return pd.read_csv(path)


def build_ratings(df: pd.DataFrame, dim: str) -> Ratings:
    """Long-format Ratings for one annotation dimension: item x {expert_0, expert_1, expert_2}."""
    long = df.rename(columns={dim: "score"})[["item", "rater", "score", "stratum"]]
    return Ratings.from_long(long, item="item", rater="rater", score="score", stratum="stratum")


def lodo_conditioner(df: pd.DataFrame, dim: str) -> dict[Hashable, float]:
    """Leave-one-dimension-out external conditioner: mean over raters of the other 3 dims.

    Independent of ``dim``'s own score by construction, which is what an external DIF
    conditioner needs.
    """
    item_dim_mean = df.groupby("item")[ALL_DIMS].mean()
    others = [d for d in ALL_DIMS if d != dim]
    comp = item_dim_mean[others].mean(axis=1)
    return dict(zip(comp.index.tolist(), comp.tolist(), strict=True))


def audit_dimension(df: pd.DataFrame, dim: str) -> ReportCard:
    """Reliability + DIF (with cluster-robust CI) report card for one dimension."""
    ratings = build_ratings(df, dim)
    conditioner = lodo_conditioner(df, dim)
    return audit(
        ratings,
        focal=FOCAL,
        reference=REFERENCE,
        conditioner=conditioner,
        robust=True,
        n_boot=N_BOOT,
        seed=SEED,
    )


def build_cards(df: pd.DataFrame) -> tuple[list[ReportCard], list[float]]:
    """Report cards for the 3 pre-registered dimensions, plus their Holm-adjusted p_total."""
    cards = [audit_dimension(df, dim) for dim in AUDITED_DIMS]
    p_holm = holm_adjust([card.dif.p_total for card in cards])
    return cards, p_holm


def render(df: pd.DataFrame, cards: list[ReportCard], p_holm: list[float]) -> str:
    counts = df.groupby("stratum")["item"].nunique().to_dict()
    lines = [
        "# metajudge: SummEval consistency/fluency/relevance DIF (pre-registered family)",
        f"_{FOCAL} vs {REFERENCE}, external leave-one-dimension-out conditioner, "
        f"Holm-corrected across {len(AUDITED_DIMS)} dimensions._",
        "",
        f"Per-stratum item N: {counts}",
        "",
    ]
    for dim, card, p_adj in zip(AUDITED_DIMS, cards, p_holm, strict=True):
        lines.append(f"## {ROLE[dim]}: {dim}")
        lines.append("")
        lines.append(card.to_markdown())
        lines.append("")
        lines.append(
            f"p_total, Holm-adjusted across the {len(AUDITED_DIMS)}-dimension family: {p_adj:.3g}"
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    df = load_data()
    cards, p_holm = build_cards(df)
    print(render(df, cards, p_holm), end="")


if __name__ == "__main__":
    main()
