"""Worked example: the report card catching a biased judge panel.

Most metajudge examples land on a reassuring result. This one is the opposite:
it shows the audit doing the job it exists for. Two simulated three-judge panels
score the same two families of outputs (a focal family and a reference family).
Their reliability numbers look almost identical, Krippendorff's alpha and ICC
both high, so the usual "are the judges consistent?" checks pass on both. Yet
one panel carries a systematic bias against the focal family: at equal underlying
quality, it scores focal outputs lower. Only the DIF pillar sees it, and it fires
Jodoin-Gierl class C on the biased panel while the clean panel stays class A.

The lesson: high agreement is not fairness. A panel can be unanimous and still be
unanimously biased against one kind of output, and averaging or agreement stats
will never surface it. DIF will.

SIMULATED, not a model run. Both panels are generated by the repository's own
data-generating process (`sim.dgp.simulate`), which plants a known, controllable
amount of true DIF (a group effect at matched latent quality, not a level shift).
Reusing that validated generator is deliberate: hand-rolling a DIF-positive panel
would risk shipping a statistically wrong demonstration. Because it imports
`sim.dgp`, this example runs from a repository checkout, not from a
`pip install metajudge` wheel.

Why an external conditioner. DIF matches focal against reference on a quality
axis. The default axis is a leave-one-rater-out rest score, but when the whole
panel shares the bias, that rest score is itself depressed for the focal family
and partially absorbs the effect (panel-relative DIF understates panel-shared
bias). So this example passes the generator's ground-truth quality score as an
explicit external conditioner. That keeps the quality axis independent of the
panel's shared bias, and it is exactly the move a real user makes when they have
an independent quality signal to match on.

Run it (no key, no network). Because it imports `sim.dgp` and is meant to be
reusable from `examples.audit_catches_bias`, run it as a module so the repo
root is on the import path, not as a bare script path:

    uv run python -m examples.audit_catches_bias
"""

from __future__ import annotations

from sim.dgp import FOCAL, REFERENCE, DgpParams, SimSample, simulate

from metajudge import ReportCard, audit

# Panel shape. 100 items per group * 3 judges * 2 groups = 600 observations, past
# the >=500 the Jodoin-Gierl thresholds were calibrated on. A strong trait slope
# and tight rater noise give both panels solid inter-judge agreement (alpha ~0.75),
# so the reliability pillar clears both and DIF is the only separator. Seed pins
# the whole demonstration.
N_ITEMS_PER_GROUP = 100
N_RATERS = 3
TRAIT_SLOPE = 4.0
RATER_SD = 0.25
SEED = 0

# The biased panel scores the focal family lower at matched latent quality.
# Negative dif_uniform lowers focal ratings; the magnitude is calibrated so the
# effect size lands comfortably past the Jodoin-Gierl class-C threshold
# (Nagelkerke R2 delta ~0.18, threshold 0.070) while alpha stays within ~0.01 of
# the clean panel. The clean panel plants no DIF. tests/test_catches_bias.py pins
# both outcomes; do not change these without re-running that test.
BIASED_DIF_UNIFORM = -3.5


def simulate_panel(dif_uniform: float) -> SimSample:
    """One three-judge panel with equal latent quality across groups (mu_focal=0)."""
    params = DgpParams(
        n_items_per_group=N_ITEMS_PER_GROUP,
        n_raters=N_RATERS,
        trait_slope=TRAIT_SLOPE,
        rater_sd=RATER_SD,
        mu_focal=0.0,
        dif_uniform=dif_uniform,
    )
    return simulate(params, seed=SEED)


def _audit_panel(sample: SimSample) -> ReportCard:
    """Audit a panel, matching on the generator's ground-truth quality score."""
    return audit(
        sample.ratings,
        focal=FOCAL,
        reference=REFERENCE,
        conditioner=sample.conditioner,
    )


def build_cards() -> tuple[ReportCard, ReportCard]:
    """Return (clean_panel_card, biased_panel_card)."""
    clean = _audit_panel(simulate_panel(0.0))
    biased = _audit_panel(simulate_panel(BIASED_DIF_UNIFORM))
    return clean, biased


def render(clean: ReportCard, biased: ReportCard) -> str:
    """Assemble the two cards and the decision narration into one report."""
    lines = [
        "# metajudge: catching a biased judge panel",
        "_SIMULATED PANELS (no model calls). focal = the output family the biased "
        "panel penalizes; reference = the other family._",
        "",
        "## Panel A: clean",
        clean.to_markdown(),
        "",
        "## Panel B: same reliability, hidden bias",
        biased.to_markdown(),
        "",
        "## What just happened",
        f"Both panels agree with themselves about equally well "
        f"(alpha {clean.alpha.alpha:.3f} clean vs {biased.alpha.alpha:.3f} biased), "
        f"so the reliability pillar clears both. But Panel B carries a systematic "
        f"bias against the focal family: at matched quality it scores those outputs "
        f"lower. The DIF pillar catches it, class {biased.dif.dif_class} against Panel "
        f"A's class {clean.dif.dif_class}.",
        "",
        "The decision this changes: if these were your LLM-judge scores, you were "
        "about to rank models on Panel B's numbers. Don't, at least not yet. Class C "
        "here flags the focal/reference split as worth investigating, not a settled "
        "instrument-level verdict. Until you have ruled that out, treat the "
        "leaderboard as confounded with output family: a model that produces more "
        "focal-style outputs may be scoring lower for the style, not the substance.",
    ]
    return "\n".join(lines)


def main() -> None:
    clean, biased = build_cards()
    print(render(clean, biased))


if __name__ == "__main__":
    main()
